# Generated by Django 4.0.2 on 2022-02-18 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.BigIntegerField(db_index=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('transaction_details', models.CharField(blank=True, max_length=500, null=True)),
                ('withdrawal_amt', models.FloatField(default=0, null=True)),
                ('deposit_amt', models.FloatField(default=0, null=True)),
                ('balance_amt', models.FloatField(default=0, null=True)),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
    ]
